CREATE PROCEDURE [dbo].[Procedure1]
	@DAT_MES INT = NULL
,	@DAT_ANO INT = NULL
,	@COD_PRODUTO CHAR(04) = NULL
,	@DES_PRODUTO VARCHAR(30) = NULL
,	@NUM_LANCAMENTO DECIMAL(18) = NULL
,	@DES_DESCRICAO VARCHAR(50) = NULL
,	@VAL_VALOR DECIMAL(18,2) = NULL
AS
BEGIN

	SET NOCOUNT ON;

	--
	--	OBTÉM A URL DA CAMPANHA
	--	
	SELECT
		[LancamentoMes] = MM.DAT_MES
	,	[LancamentoAno] = MM.DAT_ANO
	,	[ProdutoCodigo] = MM.COD_PRODUTO
	,	[ProdutoNome] = PR.DES_PRODUTO
	,	[LancamentoCosif] = MM.COD_COSIF
	,	[LancamentoNumero] = MM.NUM_LANCAMENTO
	,	[LancamentoDescricao] = MM.DES_DESCRICAO
	,	[LancamentoValor] = MM.VAL_VALOR
	,	[LancamentoDataHora] = MM.DAT_MOVIMENTO
	,	[LancamentoUsuario] = MM.COD_USUARIO

	FROM
		MOVIMENTO_MANUAL AS MM (NOLOCK)
	INNER JOIN
		PRODUTO_COSIF AS PC (NOLOCK)
	ON
		MM.COD_PRODUTO = PC.COD_PRODUTO
	AND
		MM.COD_COSIF = PC.COD_COSIF
	INNER JOIN 
		PRODUTO AS PR (NOLOCK)
	ON
		PC.COD_PRODUTO = PR.COD_PRODUTO
	WHERE
		MM.DAT_MES >= 0 
	AND
		(MM.DAT_MES = @DAT_MES OR @DAT_MES IS NULL)		
	AND
		MM.DAT_ANO >= 0
	AND
		(MM.DAT_ANO = @DAT_ANO OR @DAT_ANO IS NULL)
	AND
		MM.COD_PRODUTO >= 0
	AND
		(MM.COD_PRODUTO = @COD_PRODUTO OR @COD_PRODUTO IS NULL)
	AND 
		(PR.DES_PRODUTO = @DES_PRODUTO OR @DES_PRODUTO IS NULL)
	AND
		MM.NUM_LANCAMENTO >= 0
	AND
		(MM.NUM_LANCAMENTO = @NUM_LANCAMENTO OR @NUM_LANCAMENTO IS NULL)
	AND
		MM.VAL_VALOR >= 0 
	AND
		(MM.VAL_VALOR = @VAL_VALOR OR @VAL_VALOR IS NULL)
	ORDER BY
		MM.DAT_ANO DESC
	,	MM.DAT_MES DESC
	,	MM.NUM_LANCAMENTO DESC
	;
END
RETURN 0
