CREATE TABLE [dbo].[MOVIMENTO_MANUAL]
(
	[DAT_MES] SMALLINT NOT NULL, 
    [DAT_ANO] SMALLINT NOT NULL, 
    [NUM_LANCAMENTO] NUMERIC(18) NOT NULL, 
    [COD_PRODUTO] CHAR(4) NOT NULL, 
    [COD_COSIF] CHAR(11) NOT NULL,
	[DAT_MOVIMENTO] DATETIME NULL, 
    [VAL_VALOR] NUMERIC(18, 2) NULL, 
	[DES_DESCRICAO] VARCHAR(50) NULL,
    [COD_USUARIO] VARCHAR(15) NULL, 
    CONSTRAINT [PK_MovimentoManual] PRIMARY KEY CLUSTERED 
	(
		[DAT_MES] ASC,
		[DAT_ANO] ASC,
		[NUM_LANCAMENTO] ASC,
		[COD_PRODUTO] ASC,
		[COD_COSIF] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO 


ALTER TABLE [dbo].[MOVIMENTO_MANUAL] ADD
CONSTRAINT [FK_MovimentoManual_COD_PRODUTO_COD_COSIF_ProdutoCosif_COD_PRODUTO_COD_COSIF] FOREIGN KEY
(
	[COD_PRODUTO],
	[COD_COSIF]
) REFERENCES [dbo].[PRODUTO_COSIF] (
	[COD_PRODUTO],
	[COD_COSIF]
) 
GO
