CREATE TABLE [dbo].[PRODUTO_COSIF]
(
	[COD_PRODUTO] CHAR(4) NOT NULL, 
    [COD_COSIF] CHAR(11) NOT NULL, 
    [COD_CLASSIFICACAO] CHAR(6) NULL, 
    [STA_STATUS] NCHAR(10) NULL, 
	CONSTRAINT [PK_ProdutoCosif] PRIMARY KEY CLUSTERED 
	(
		[COD_PRODUTO] ASC, [COD_COSIF] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO 

ALTER TABLE [dbo].[PRODUTO_COSIF] ADD
CONSTRAINT [FK_ProdutoCosif_COD_PRODUTO_Produto_COD_PRODUTO] FOREIGN KEY
(
	[COD_PRODUTO]
) REFERENCES [dbo].[PRODUTO] (
	[COD_PRODUTO]
) 
GO